name: Test Build
on:
    push:
        branches: [main]
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]
        branches: [main]

jobs:
    build:
        name: "Test compile linux-x86_64"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install Libraries
              run: sudo apt install libpng-dev
            
            - name: Build optar-ark
              run: make all